name: 'metamask-mobile-build-version'
description: 'Generates a build version for MetaMask Mobile.'

runs:
  using: 'node20'
  main: './action/index.js'

inputs:
  github-token:
    description: 'A Personal Access Token or the Github Token with Write-Access to Pull Requests. If none provided it will use the default Github Token.'
    default: ${{ github.token }}
    required: false

outputs:
  build-version:
    description: 'Latest build version.'