name: 'metamask-mobile-build-version'
description: 'Generates a build version for MetaMask Mobile.'

runs:
  using: 'node20'
  main: './action/index.js'

inputs:
  build-version-table:
    default: 'metamask-mobile-build-version'
    description: 'The name of the table to store the build version.'
    required: false
  build-version-key:
    default: 'metamask-mobile'
    description: 'The key to store the build version under.'
    required: false
  lock-table:
    default: 'metamask-mobile-build-version-lock'
    description: 'The name of the table to store lock records.'
    required: false
  lock-key:
    default: ''
    description: 'Identifier used for the lock. Defaults to <build-version-table>#<build-version-key>.'
    required: false
  lock-lease-duration-seconds:
    default: '60'
    description: 'Length of time the lock is held before expiring automatically.'
    required: false
  lock-wait-timeout-seconds:
    default: '300'
    description: 'Total time to wait for the lock before failing.'
    required: false
  lock-poll-interval-seconds:
    default: '5'
    description: 'Interval between retries when waiting for the lock.'
    required: false
  github-token:
    description: 'The GitHub'
    required: true

outputs:
  build-version:
    description: 'Latest build version.'
