name: 'metamask-mobile-build-version'
description: 'Generates a build version for MetaMask Mobile.'

runs:
  using: 'node20'
  main: './action/index.js'

inputs:
  build-version-table:
    default: 'metamask-mobile-build-version'
    description: 'The name of the table to store the build version.'
    required: false

outputs:
  build-version:
    description: 'Latest build version.'